openapi: "3.0.0"
info:
  version: 1.0.0
  title: ClientsApp
  license:
    name: HxH
servers:
  - url: http://localhost:8080/
paths:
  /client:
    get:
      summary: List all clients
      operationId: clientList
      tags:
        - clients
      responses:
        '200':
          description: OK
          headers:
            x-next:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clients"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Create a client
      operationId: createClient
      tags:
        - clients
      parameters:
        - name: client
          in: query
          description: Some information about the created client
          required: true
          schema:
            type: clientDTO
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /client/{clientId}:
    get:
      summary: Info for a specific client
      operationId: showClientById
      tags:
        - clients
      parameters:
        - name: clientId
          in: path
          required: true
          description: The id of the client to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Client:
      type: object
      required:
        - id
        - name
        - number
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        number:
          type: string
        tag:
          type: string
    Clients:
      type: array
      items:
        $ref: '#/components/schemas/ClientDTO'
    ClientDTO:
      type: object
      required:
        - name
        - number
      properties:
        name:
          type: string
        number:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string